export const vibe = {
  colors: {
    primitive: {
      nearBlack: { 900: '#1a1a18', 800: '#2d2d2b', 950: '#080807' },
      lime:      { 400: '#d5eb47' },
      warm:      { 300: '#c3a882' },
      neutral:   { 0: '#ffffff', 50: '#f8fafc', 400: '#636363', 200: '#c2c7d7' },
    },
    semantic: {
      background: {
        page:           '#ffffff',
        surface:        '#f8fafc',
        inverse:        '#1a1a18',
        inverseDeep:    '#111110',
        inverseDeepest: '#080807',
        accent:         '#d5eb47',
      },
      text: {
        primary:        '#1a1a18',
        secondary:      '#636363',
        onInverse:      '#ffffff',
        onInverseMuted: 'rgba(255,255,255,0.6)',
        accent:         '#d5eb47',
        accentWarm:     '#c3a882',
      },
      border: {
        default:  '#1a1a18',
        subtle:   '#c2c7d7',
        accent:   '#d5eb47',
      },
      action: {
        primary:   { background: '#1a1a18', foreground: '#ffffff' },
        secondary: { background: '#ffffff', foreground: '#1a1a18' },
      },
    },
  },
  typography: {
    fonts: {
      display: '"Bricolage Grotesque", sans-serif',
      heading: '"Bricolage Grotesque", sans-serif',
      body:    'Geist',
      ui:      'Geist',
    },
    weights: {
      display:    700,
      heading:    700,
      subheading: 600,
      body:       400,
      ui:         700,
      label:      500,
    },
    sizes: {
      display: '96px',
      h1:      '72px',
      h2:      '40px',
      h3:      '36px',
      h4:      '24px',
      h5:      '20px',
      bodyLg:  '20px',
      body:    '16px',
      bodySm:  '14px',
      label:   '12px',
      micro:   '11px',
    },
    tracking: {
      display:  '-3.84px',
      h1:       '-2.16px',
      h2:       '0px',
      eyebrow:  '4px',
      nav:      '1.12px',
      button:   '1.92px',
      bodySm:   '1.68px',
      label:    '0.4px',
      body:     '0px',
    },
    lineHeight: {
      display: '96px',
      h1:      '82.8px',
      bodyLg:  '28px',
      body:    '20px',
      bodySm:  '20px',
    },
  },
  spacing: {
    section:   { vertical: '120px', horizontal: '48px', gap: '24px' },
    layout:    { containerGap: '24px', cardGap: '24px' },
    component: { lg: '32px', md: '20px', sm: '8px', gapLg: '24px', gapMd: '16px', gapSm: '8px' },
  },
  radius: {
    none: '0px',
    sm:   '4px',
    md:   '16px',
    lg:   '24px',
    pill: '120px',
  },
} as const;
